services:
  wufeng-tv:
    image: ghcr.io/xyf0104/moontvplus:latest
    container_name: wufeng-tv
    restart: on-failure
    ports:
      - '3000:3000'
    environment:
      - USERNAME=${TV_USERNAME}
      - PASSWORD=${TV_PASSWORD}
      - NEXT_PUBLIC_STORAGE_TYPE=kvrocks
      - KVROCKS_URL=redis://wufeng-kvrocks:6666
    networks:
      - wufeng-network
    depends_on:
      - wufeng-kvrocks
  wufeng-kvrocks:
    image: apache/kvrocks
    container_name: wufeng-kvrocks
    restart: unless-stopped
    volumes:
      - kvrocks-data:/var/lib/kvrocks
    networks:
      - wufeng-network
networks:
  wufeng-network:
    driver: bridge
volumes:
  kvrocks-data:
